version: 2

jobs:

  build:
    docker:
      - image: rust:1
    steps:
      - checkout
      - run: 
          name: Install nightly
          command: rustup toolchain install nightly
      - run: 
          name: Setup rust nightly default
          command: rustup default nightly
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - run:
           name: install clippy
           command: rustup component add clippy
      - run:
           name: run clippy
           command: cargo clippy
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Run all tests
          command: cargo test --all

  
